FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

RUN npm install
RUN npm run db:generate

RUN cd apps/user-app && npx next build

WORKDIR /usr/src/app/apps/user-app

CMD ["npx", "next", "start"]
